name: Silver Layer ETL

on:
  schedule:
    - cron: "*/5 * * * *" # runs every 5min
  workflow_dispatch: # allows manual execution

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Aktualizacja z v3 na v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Aktualizacja z v4 na v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Silver Layer Script
        env:
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
        run: python src/silver_layer.py
