name: Silver Layer ETL

on:
  schedule:
    - cron: "*/5 * * * *" # Uruchamiaj co 5 minut
  workflow_dispatch: # Pozwala na ręczne uruchomienie przyciskiem "Run workflow"

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Silver Layer Script
        # Tutaj przekazujemy sekrety z GitHuba do skryptu Pythona
        env:
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
        run: python src/silver_layer.py
