name: IoT ETL Pipeline

on:
  schedule:
    - cron: '*/5 * * * *' # Uruchamiaj co 5 minut (GitHub ma limity na częstsze akcje)
  workflow_dispatch: # Pozwala odpalić ręcznie dla testu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install influxdb-client pandas

      - name: Run ETL Script
        env:
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }} # Token ukryty w ustawieniach repo
        run: python your_script_name.py
